services:

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - .env